send_message:
  name: Send Message
  description: Sends a chat message
  fields:
    message:
      required: true
      selector:
        text:

get_history:
  name: Get History
  description: Load chat history

clear_chat:
  name: Clear Chat
  description: Deletes all messages